name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: gabrieljeronimodev
          outputs: |
            dist/github-snake.svg?color_snake=#0052CC&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39
            dist/github-snake-dark.svg?color_snake=#58e8ff&color_dots=#161b22,#0d2845,#0052cc,#1a75ff,#4d9fff

      - name: Push output to branch "output"
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          force_orphan: true
